package com.loud9ja.loud9ja.stream.ui.meeting

enum class RecordingState {
    RECORDING,
    NOT_RECORDING_OR_STREAMING,
    RECORDING_TRANSITIONING_TO_NOT_RECORDING,
    NOT_RECORDING_TRANSITION_IN_PROGRESS,
    STREAMING,
    STREAMING_AND_RECORDING
}